spring.application.name=registration-service
server.port=8083

spring.datasource.url=${REGISTRATION_DB_URL:jdbc:mysql://localhost:2000/registration_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${REGISTRATION_DB_USERNAME:root}
spring.datasource.password=${REGISTRATION_DB_PASSWORD:6666}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

course-service.base-url=${COURSE_SERVICE_BASE_URL:http://localhost:8085}
course-service.connect-timeout=3s
course-service.read-timeout=5s

jwt.secret=${JWT_SECRET:CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te}
